version: '3.4'

services:
  postgre:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'

volumes:
  tfr-postgres:
  redis:
